#include "fatfs_test.h"
#include "main.h"
#include "fatfs.h"

#include <stdio.h>
#include <string.h>

extern UART_HandleTypeDef huart1;

static void uart_print(const char *text)
{
    HAL_UART_Transmit(&huart1,
                      (uint8_t *)text,
                      strlen(text),
                      HAL_MAX_DELAY);
}

void FATFS_Test_ReadOnly(void)
{
    FRESULT res;
    DIR dir;
    FILINFO fno;
    char text[160];

    uart_print("\r\n--- FATFS READ-ONLY TEST ---\r\n");

    /*
     * Mount immediately.
     * SDFatFS and SDPath are generated by CubeMX.
     */
    res = f_mount(&SDFatFS, (TCHAR const *)SDPath, 1);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_mount() = %d\r\n",
                 (int)res);

        uart_print(text);
        return;
    }

    uart_print("FAT32 mount OK\r\n");

    /*
     * Open root directory.
     */
    res = f_opendir(&dir, SDPath);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_opendir() = %d\r\n",
                 (int)res);

        uart_print(text);

        f_mount(NULL, (TCHAR const *)SDPath, 0);
        return;
    }

    uart_print("\r\nRoot directory:\r\n");

    while (1)
    {
        res = f_readdir(&dir, &fno);

        if (res != FR_OK)
        {
            snprintf(text, sizeof(text),
                     "FATFS ERROR: f_readdir() = %d\r\n",
                     (int)res);

            uart_print(text);
            break;
        }

        /* End of directory */
        if (fno.fname[0] == 0)
        {
            break;
        }

        if (fno.fattrib & AM_DIR)
        {
            snprintf(text, sizeof(text),
                     "[DIR ] %s\r\n",
                     fno.fname);
        }
        else
        {
            snprintf(text, sizeof(text),
                     "[FILE] %-12s %lu bytes\r\n",
                     fno.fname,
                     (unsigned long)fno.fsize);
        }

        uart_print(text);
    }

    f_closedir(&dir);

    uart_print("\r\n--- FATFS READ TEST PASSED ---\r\n");
}


void FATFS_Test_ReadWrite(void)
{
    FRESULT res;
    FIL file;
    UINT bytes_written;
    UINT bytes_read;

    char text[160];

    static const char test_data[] =
        "BusAnalyzerII STM32H725 FatFs read/write test\r\n";

    char read_buffer[128];

    uart_print("\r\n--- FATFS READ/WRITE TEST ---\r\n");


    /* -----------------------------------------------------
     * Mount filesystem
     * ----------------------------------------------------- */

    res = f_mount(&SDFatFS, (TCHAR const *)SDPath, 1);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_mount() = %d\r\n",
                 (int)res);

        uart_print(text);
        return;
    }

    uart_print("Filesystem mount OK\r\n");


    /* -----------------------------------------------------
     * Create test file
     *
     * FA_CREATE_ALWAYS:
     * - create file if it doesn't exist
     * - overwrite STM32TST.TXT if it already exists
     * ----------------------------------------------------- */

    res = f_open(&file,
                 "STM32TST.TXT",
                 FA_CREATE_ALWAYS | FA_WRITE);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_open(write) = %d\r\n",
                 (int)res);

        uart_print(text);
        return;
    }

    uart_print("STM32TST.TXT opened for write\r\n");


    /* -----------------------------------------------------
     * Write test data
     * ----------------------------------------------------- */

    bytes_written = 0;

    res = f_write(&file,
                  test_data,
                  strlen(test_data),
                  &bytes_written);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_write() = %d\r\n",
                 (int)res);

        uart_print(text);

        f_close(&file);
        return;
    }

    snprintf(text, sizeof(text),
             "Written %u bytes\r\n",
             bytes_written);

    uart_print(text);


    if (bytes_written != strlen(test_data))
    {
        uart_print("FATFS ERROR: incomplete write\r\n");

        f_close(&file);
        return;
    }


    /* Explicitly flush FAT/data to card */

    res = f_sync(&file);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_sync() = %d\r\n",
                 (int)res);

        uart_print(text);

        f_close(&file);
        return;
    }


    /* Close the file */

    res = f_close(&file);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_close(write) = %d\r\n",
                 (int)res);

        uart_print(text);
        return;
    }

    uart_print("File write/close OK\r\n");


    /* -----------------------------------------------------
     * Reopen file READ ONLY
     * ----------------------------------------------------- */

    res = f_open(&file,
                 "STM32TST.TXT",
                 FA_READ);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_open(read) = %d\r\n",
                 (int)res);

        uart_print(text);
        return;
    }


    /* -----------------------------------------------------
     * Read it back
     * ----------------------------------------------------- */

    memset(read_buffer, 0, sizeof(read_buffer));

    bytes_read = 0;

    res = f_read(&file,
                 read_buffer,
                 sizeof(read_buffer) - 1,
                 &bytes_read);

    if (res != FR_OK)
    {
        snprintf(text, sizeof(text),
                 "FATFS ERROR: f_read() = %d\r\n",
                 (int)res);

        uart_print(text);

        f_close(&file);
        return;
    }

    f_close(&file);



    FILINFO file_info;

    if (f_stat("STM32TST.TXT", &file_info) == FR_OK)
    {
        uint16_t year;
        uint8_t month;
        uint8_t day;
        uint8_t hour;
        uint8_t minute;
        uint8_t second;

        year   = 1980U + ((file_info.fdate >> 9) & 0x7FU);
        month  = (file_info.fdate >> 5) & 0x0FU;
        day    = file_info.fdate & 0x1FU;

        hour   = (file_info.ftime >> 11) & 0x1FU;
        minute = (file_info.ftime >> 5) & 0x3FU;
        second = (file_info.ftime & 0x1FU) * 2U;

        snprintf(text, sizeof(text),"FatFs timestamp: %04u-%02u-%02u %02u:%02u:%02u\r\n",
               year,
               month,
               day,
               hour,
               minute,
               second);
        uart_print(text);
    }

    snprintf(text, sizeof(text),
             "Read back %u bytes\r\n",
             bytes_read);

    uart_print(text);

    uart_print("Content: ");
    uart_print(read_buffer);



    /* -----------------------------------------------------
     * Verify exact contents
     * ----------------------------------------------------- */

    if ((bytes_read == strlen(test_data)) &&
        (memcmp(read_buffer,
                test_data,
                strlen(test_data)) == 0))
    {
        uart_print("\r\nFATFS VERIFY: PASS\r\n");
        uart_print("--- FATFS READ/WRITE TEST PASSED ---\r\n");
    }
    else
    {
        uart_print("\r\nFATFS VERIFY: FAILED\r\n");
    }
}
